/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_evidence_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_requests_get"];
        put?: never;
        /** Create */
        post: operations["create_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_requests__request_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Feedback */
        post: operations["record_feedback_requests__request_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_requests__request_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/evaluation/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Evaluation */
        post: operations["cancel_evaluation_requests__request_id__evaluation_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_requests__request_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_requests__request_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change State */
        post: operations["change_state_demo_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Virtual Time */
        post: operations["advance_virtual_time_demo_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sample Virtual State */
        post: operations["sample_virtual_state_demo_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Virtual State */
        post: operations["reset_virtual_state_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/review-contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Contact */
        get: operations["review_contact_requests__request_id__review_contact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Request Notifications */
        get: operations["request_notifications_requests__request_id__notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/notifications/{notification_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Notification */
        post: operations["send_notification_requests__request_id__notifications__notification_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppliedExecution */
        AppliedExecution: {
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @constant
             */
            status: "applied";
            /**
             * Virtual
             * @constant
             */
            virtual: true;
            command: components["schemas"]["Command-Output"];
            state: components["schemas"]["Snapshot"];
        };
        /** Approval */
        Approval: {
            /** Actor */
            actor: string;
            /** Report Digest */
            report_digest: string;
            /** Expires At */
            expires_at: number;
            /** Reason */
            reason: string;
        };
        /** AuditEvent */
        AuditEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "created" | "evaluation_failed" | "evaluated" | "approve" | "reject" | "execution_denied" | "execution_reserved" | "executed" | "execution_unknown" | "evaluation_interrupted" | "execution_interrupted" | "evaluation_started" | "request_retest" | "notification_queued" | "notification_sending" | "notification_sent" | "notification_unknown";
            /** At */
            at: number;
            /** Verdict */
            verdict: ("draft" | "evaluating" | "blocked" | "hold" | "awaiting_approval" | "approved" | "rejected" | "revalidation_required" | "executing" | "completed" | "execution_unknown") | null;
            /** Report Digest */
            report_digest: string | null;
            /** Actor */
            actor: string | null;
            /** Reason */
            reason: string | null;
            /** Execution Id */
            execution_id: string | null;
        };
        /** BranchAssessment */
        BranchAssessment: {
            /** Peak C */
            peak_c: number;
            /** First Exceeded S */
            first_exceeded_s: number | null;
            /** Equilibrium C */
            equilibrium_c: number | null;
            /**
             * Equilibrium Status
             * @enum {string}
             */
            equilibrium_status: "finite" | "unbounded_heating" | "no_unique_equilibrium";
            /** Thermal Time Constant S */
            thermal_time_constant_s: number | null;
        };
        /** Command */
        "Command-Input": {
            /**
             * Type
             * @default set_pump_speed
             * @constant
             */
            type: "set_pump_speed";
            /** Target Pct */
            target_pct: number;
            /**
             * Duration S
             * @default 300
             */
            duration_s: number;
        };
        /** Command */
        "Command-Output": {
            /**
             * Type
             * @default set_pump_speed
             * @constant
             */
            type: "set_pump_speed";
            /** Target Pct */
            target_pct: number;
            /**
             * Duration S
             * @default 300
             */
            duration_s: number;
        };
        /** DecisionInput */
        DecisionInput: {
            /** Report Digest */
            report_digest: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject" | "request_retest";
            /** Reason */
            reason: string;
        };
        /** DecisionReport */
        DecisionReport: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Revision */
            revision: number;
            /** Command Digest */
            command_digest: string;
            /** Snapshot */
            snapshot: components["schemas"]["Snapshot"] | components["schemas"]["TEPState"];
            /** Snapshot Digest */
            snapshot_digest: string;
            /** Model Version */
            model_version: string;
            /** Policy Version */
            policy_version: string;
            /**
             * Execution Scope
             * @default unconfigured
             * @enum {string}
             */
            execution_scope: "virtual" | "unconfigured";
            /** Mock */
            mock: boolean;
            /** Can Approve */
            can_approve: boolean;
            evidence: components["schemas"]["EvidenceReview"] | null;
            simulation: components["schemas"]["SimulationResult"] | null;
            tep_simulation: components["schemas"]["TEPResult"] | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "blocked" | "hold" | "awaiting_approval";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "INVALID_STATE" | "POLICY_VIOLATION" | "LIMIT_EXCEEDED" | "DEMO_PASS" | "EVIDENCE_INCOMPLETE" | "SIMULATION_INCOMPLETE" | "MODULE_FAILURE" | "MATERIAL_DEVIATION" | "LIVE_POLICY_NOT_CONFIGURED" | "DEMO_POLICY_OUT_OF_SCOPE" | "EVALUATION_CONTEXT_CHANGED" | "EVALUATION_TIMEOUT" | "EVALUATION_CANCELLED" | "WORKER_FAILURE" | "TEP_POLICY_NOT_CONFIGURED";
            /** Reason */
            reason: string;
            /** Digest */
            digest: string;
            assessment: components["schemas"]["ReviewAssessment"] | null;
        };
        /** DemoAdvanceInput */
        DemoAdvanceInput: {
            /** Seconds S */
            seconds_s: number;
        };
        /** DemoStateInput */
        DemoStateInput: {
            /** Load Ratio */
            load_ratio: number;
            /**
             * Sensor Quality
             * @default valid
             * @enum {string}
             */
            sensor_quality: "valid" | "invalid";
        };
        /** DeviationMetric */
        DeviationMetric: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "normal" | "degraded_cooling";
            /** Baseline Peak C */
            baseline_peak_c: number;
            /** Candidate Peak C */
            candidate_peak_c: number;
            /** Absolute Delta C */
            absolute_delta_c: number;
            /** Material */
            material: boolean | null;
        };
        /** EvaluationTask */
        EvaluationTask: {
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed" | "timed_out" | "cancelled" | "interrupted";
            /** Started At */
            started_at: number;
            /** Deadline At */
            deadline_at: number;
            /** Finished At */
            finished_at: number | null;
        };
        /** EvidenceCard */
        EvidenceCard: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "support" | "counter" | "limitation";
            /** Claim */
            claim: string;
            /**
             * Applicability
             * @enum {string}
             */
            applicability: "applicable" | "partial" | "mismatch" | "unknown";
            /** Locator */
            locator: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "team_authored_fixture" | "team_authored_demo" | "paper" | "manual" | "field_record";
            /** Excerpt */
            excerpt: string | null;
            /** Publisher */
            publisher: string | null;
            /** Version */
            version: string | null;
            /** Published At */
            published_at: string | null;
            /** Usage */
            usage: string | null;
            /** Proposed Test */
            proposed_test: "degraded_cooling" | null;
            /** Parameter Origin */
            parameter_origin: "demo_assumption" | null;
            /** Matched Conditions */
            matched_conditions: string[];
            /** Missing Conditions */
            missing_conditions: string[];
        };
        /** EvidenceCatalog */
        EvidenceCatalog: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "fixture" | "live" | "invalid";
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "local" | "europepmc" | "invalid";
            /** Api Key Configured */
            api_key_configured: boolean;
            /** Model Configured */
            model_configured: boolean;
            /** Ready */
            ready: boolean;
            /** Sources */
            sources: components["schemas"]["EvidenceSourceSummary"][];
            /** Issues */
            issues: string[];
            /** Catalog Error */
            catalog_error: boolean;
        };
        /** EvidenceReview */
        EvidenceReview: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mock */
            mock: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "demo_fixture" | "completed" | "insufficient" | "failed";
            /** Cards */
            cards: components["schemas"]["EvidenceCard"][];
            /** Proposed Tests */
            proposed_tests: components["schemas"]["Scenario"][];
            /** Limitation */
            limitation: string;
        };
        /** EvidenceSourceSummary */
        EvidenceSourceSummary: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Source Url */
            source_url: string | null;
            /** Publisher */
            publisher: string;
            /** Locator */
            locator: string;
        };
        /** ExecutionInput */
        ExecutionInput: {
            /** Report Digest */
            report_digest: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewRequest */
        "NewRequest-Input": {
            /**
             * Equipment Id
             * @default cooling-demo-01
             * @enum {string}
             */
            equipment_id: "cooling-demo-01" | "tep-sim-01";
            /**
             * Purpose
             * @default 냉각 펌프 속도 변경 검토
             */
            purpose: string;
            /** Command */
            command: components["schemas"]["Command-Input"] | components["schemas"]["TEPCommand-Input"];
            /** Requester Contact */
            requester_contact?: string | null;
        };
        /** NewRequest */
        "NewRequest-Output": {
            /**
             * Equipment Id
             * @default cooling-demo-01
             * @enum {string}
             */
            equipment_id: "cooling-demo-01" | "tep-sim-01";
            /**
             * Purpose
             * @default 냉각 펌프 속도 변경 검토
             */
            purpose: string;
            /** Command */
            command: components["schemas"]["Command-Output"] | components["schemas"]["TEPCommand-Output"];
        };
        /** Notification */
        Notification: {
            /** Id */
            id: string;
            /** Request Id */
            request_id: string;
            /** Report Digest */
            report_digest: string;
            /** Recipient */
            recipient: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "not_configured" | "queued" | "sending" | "sent" | "unknown";
            /** Created At */
            created_at: number;
            /** Sent At */
            sent_at: number | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Detail */
            detail: string;
        };
        /** ParameterRange */
        ParameterRange: {
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** PhysicalAssessment */
        PhysicalAssessment: {
            /**
             * Version
             * @default cooling-assessment-v4
             * @constant
             */
            version: "cooling-assessment-v4";
            /** Horizon S */
            horizon_s: number;
            baseline: components["schemas"]["BranchAssessment"];
            candidate: components["schemas"]["BranchAssessment"];
            /**
             * Parameter Origin
             * @default demo_assumption
             * @constant
             */
            parameter_origin: "demo_assumption";
            /**
             * Calibration Status
             * @default not_calibrated
             * @constant
             */
            calibration_status: "not_calibrated";
            /** Parameter Ranges */
            parameter_ranges: {
                [key: string]: components["schemas"]["ParameterRange"];
            };
            sensitivity: components["schemas"]["SensitivityAssessment"];
        };
        /** RecordFeedback */
        RecordFeedback: {
            /** Request Id */
            request_id: string;
            /** Record Revision */
            record_revision: number;
            /** Record Digest */
            record_digest: string;
            /** Report Digest */
            report_digest: string | null;
            /** Generated At */
            generated_at: number;
            /** Model */
            model: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "insufficient";
            /**
             * Advisory Only
             * @default true
             * @constant
             */
            advisory_only: true;
            /** Summary */
            summary: string;
            /** Result Interpretation */
            result_interpretation: string;
            /** Model Limitations */
            model_limitations: string[];
            /** Missing Conditions */
            missing_conditions: string[];
            /** Recommended Checks */
            recommended_checks: string[];
            evidence: components["schemas"]["EvidenceReview"];
        };
        /** RequestHistory */
        RequestHistory: {
            /** Reports */
            reports: components["schemas"]["DecisionReport"][];
            /** Approvals */
            approvals: components["schemas"]["Approval"][];
        };
        /** RequestRecord */
        RequestRecord: {
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            request: components["schemas"]["NewRequest-Output"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "evaluating" | "blocked" | "hold" | "awaiting_approval" | "approved" | "rejected" | "revalidation_required" | "executing" | "completed" | "execution_unknown";
            report: components["schemas"]["DecisionReport"] | null;
            approval: components["schemas"]["Approval"] | null;
            /** Execution */
            execution: components["schemas"]["AppliedExecution"] | components["schemas"]["UnknownExecution"] | null;
            /** Events */
            events: components["schemas"]["AuditEvent"][];
            evaluation: components["schemas"]["EvaluationTask"] | null;
        };
        /** ReviewAssessment */
        ReviewAssessment: {
            /**
             * Comparison
             * @default baseline_candidate_peak
             * @constant
             */
            comparison: "baseline_candidate_peak";
            /**
             * Origin
             * @default synthetic_model
             * @constant
             */
            origin: "synthetic_model";
            /** Threshold C */
            threshold_c: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "threshold_not_configured" | "within_tolerance" | "material_deviation";
            /** Metrics */
            metrics: components["schemas"]["DeviationMetric"][];
            /** Limitation */
            limitation: string;
        };
        /** ReviewContact */
        ReviewContact: {
            /** Requester Contact */
            requester_contact: string | null;
            /**
             * Verified
             * @default false
             * @constant
             */
            verified: false;
        };
        /** Scenario */
        Scenario: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "normal" | "degraded_cooling";
            /** Evidence Id */
            evidence_id: string | null;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "normal" | "degraded_cooling";
            /** Evidence Id */
            evidence_id: string | null;
            /** Baseline Peak C */
            baseline_peak_c: number;
            /** Candidate Peak C */
            candidate_peak_c: number;
            /** Limit C */
            limit_c: number;
            /** Exceeded */
            exceeded: boolean;
            /**
             * Value Origin
             * @enum {string}
             */
            value_origin: "hardcoded_demo_fixture" | "model_calculation";
            physical_assessment: components["schemas"]["PhysicalAssessment"] | null;
        };
        /** SensitivityAssessment */
        SensitivityAssessment: {
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "out_of_domain";
            /** Baseline Worst Peak C */
            baseline_worst_peak_c: number | null;
            /** Candidate Worst Peak C */
            candidate_worst_peak_c: number | null;
            /** Baseline Worst Equilibrium C */
            baseline_worst_equilibrium_c: number | null;
            /** Candidate Worst Equilibrium C */
            candidate_worst_equilibrium_c: number | null;
            /** Evaluated Parameter Sets */
            evaluated_parameter_sets: number;
            /** Limitation */
            limitation: string;
        };
        /** SessionInfo */
        SessionInfo: {
            /**
             * Role
             * @enum {string}
             */
            role: "operator" | "approver";
            /** Actor Label */
            actor_label: string;
            /**
             * Authentication
             * @default demo_token
             * @constant
             */
            authentication: "demo_token";
            /**
             * Storage
             * @default sqlite
             * @constant
             */
            storage: "sqlite";
            /** Synthetic Approval Enabled */
            synthetic_approval_enabled: boolean;
            /** Negligible Delta C */
            negligible_delta_c: number | null;
            /** Notification Configured */
            notification_configured: boolean;
            /**
             * Virtual Only
             * @default true
             * @constant
             */
            virtual_only: true;
        };
        /** SimulationResult */
        SimulationResult: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mock */
            mock: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "out_of_domain" | "failed";
            /** Model Version */
            model_version: string;
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioResult"][];
            /** Limitation */
            limitation: string;
        };
        /** Snapshot */
        Snapshot: {
            /** Revision */
            revision: number;
            /** Temperature C */
            temperature_c: number;
            /** Load Ratio */
            load_ratio: number;
            /** Pump Speed Pct */
            pump_speed_pct: number;
            /** Observed At */
            observed_at: number;
            /**
             * Sensor Quality
             * @default valid
             * @enum {string}
             */
            sensor_quality: "valid" | "invalid";
            /**
             * Data Origin
             * @default synthetic
             * @constant
             */
            data_origin: "synthetic";
            /** Target Pump Speed Pct */
            target_pump_speed_pct: number | null;
            /**
             * Simulation Time S
             * @default 0
             */
            simulation_time_s: number;
            /** Model Version */
            model_version: string | null;
            /** Calculated At */
            calculated_at: number | null;
            /**
             * Domain Status
             * @default ready
             * @enum {string}
             */
            domain_status: "ready" | "out_of_domain";
            /** Domain Reason */
            domain_reason: string | null;
        };
        /** TEPBranch */
        TEPBranch: {
            /** Points */
            points: components["schemas"]["TEPPoint"][];
            /** Csv Sha256 */
            csv_sha256: string;
        };
        /** TEPCommand */
        "TEPCommand-Input": {
            /**
             * Type
             * @constant
             */
            type: "set_tep_cooling_water";
            /**
             * Variable
             * @enum {string}
             */
            variable: "XMV10" | "XMV11";
            /** Value */
            value: number;
            /**
             * Duration S
             * @default 600
             */
            duration_s: number;
            /**
             * Sample Period S
             * @default 10
             */
            sample_period_s: number;
        };
        /** TEPCommand */
        "TEPCommand-Output": {
            /**
             * Type
             * @constant
             */
            type: "set_tep_cooling_water";
            /**
             * Variable
             * @enum {string}
             */
            variable: "XMV10" | "XMV11";
            /** Value */
            value: number;
            /**
             * Duration S
             * @default 600
             */
            duration_s: number;
            /**
             * Sample Period S
             * @default 10
             */
            sample_period_s: number;
        };
        /** TEPConfiguration */
        TEPConfiguration: {
            /**
             * Variable
             * @enum {string}
             */
            variable: "XMV10" | "XMV11";
            /** Candidate Value */
            candidate_value: number;
            /** Horizon S */
            horizon_s: number;
            /** Sample Period S */
            sample_period_s: number;
            /**
             * Integration Step S
             * @default 0.1
             * @constant
             */
            integration_step_s: 0.1;
            /**
             * Integrator
             * @default forward_euler
             * @constant
             */
            integrator: "forward_euler";
            /**
             * Controller
             * @default none_open_loop_hold
             * @constant
             */
            controller: "none_open_loop_hold";
            /**
             * Operating Mode
             * @default original_teinit_base_case
             * @constant
             */
            operating_mode: "original_teinit_base_case";
            /**
             * Random Seed
             * @default 1431655765
             * @constant
             */
            random_seed: 1431655765;
            /** Disturbances */
            disturbances: number[];
        };
        /** TEPMetric */
        TEPMetric: {
            /** Baseline Min */
            baseline_min: number;
            /** Baseline Max */
            baseline_max: number;
            /** Candidate Min */
            candidate_min: number;
            /** Candidate Max */
            candidate_max: number;
            /** Final Delta */
            final_delta: number;
            /** Max Abs Delta */
            max_abs_delta: number;
        };
        /** TEPPoint */
        TEPPoint: {
            /** Time S */
            time_s: number;
            /** Xmv */
            xmv: number[];
            /** Xmeas */
            xmeas: number[];
            /** Actual Cooling Setting */
            actual_cooling_setting: number[];
        };
        /** TEPProvenance */
        TEPProvenance: {
            /** Source Url */
            source_url: string;
            /** Source Commit */
            source_commit: string;
            /** Source Files Sha256 */
            source_files_sha256: {
                [key: string]: string;
            };
            /** Wrapper Sha256 */
            wrapper_sha256: string;
            /** Binary Sha256 */
            binary_sha256: string;
            /** Compiler */
            compiler: string;
            /** Compiler Flags */
            compiler_flags: string[];
            /** Platform */
            platform: string;
            /** Initial State */
            initial_state: number[];
            /** Initial Xmv */
            initial_xmv: number[];
            /** Initial State Sha256 */
            initial_state_sha256: string;
            /** License */
            license: string;
        };
        /** TEPResult */
        TEPResult: {
            /**
             * Schema Version
             * @default tep-1.0
             * @constant
             */
            schema_version: "tep-1.0";
            /**
             * Data Origin
             * @default simulation
             * @constant
             */
            data_origin: "simulation";
            /**
             * Mock
             * @default false
             * @constant
             */
            mock: false;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "out_of_domain" | "failed";
            /** Model Version */
            model_version: string;
            configuration: components["schemas"]["TEPConfiguration"];
            /** Variables */
            variables: {
                [key: string]: components["schemas"]["TEPVariable"];
            };
            /** Core Shutdown Rules */
            core_shutdown_rules: components["schemas"]["TEPShutdownRule"][];
            provenance: components["schemas"]["TEPProvenance"] | null;
            baseline: components["schemas"]["TEPBranch"] | null;
            candidate: components["schemas"]["TEPBranch"] | null;
            /** Comparison */
            comparison: {
                [key: string]: components["schemas"]["TEPMetric"];
            };
            /** Failure Code */
            failure_code: string | null;
            /** Detail */
            detail: string;
            /**
             * Field Validation
             * @default not_performed_no_measured_data
             * @constant
             */
            field_validation: "not_performed_no_measured_data";
        };
        /** TEPShutdownRule */
        TEPShutdownRule: {
            /** Quantity */
            quantity: string;
            /** Unit */
            unit: string;
            /** Minimum */
            minimum: number | null;
            /** Maximum */
            maximum: number | null;
            /**
             * Source
             * @default nist_tefunc_internal_shutdown
             * @constant
             */
            source: "nist_tefunc_internal_shutdown";
        };
        /** TEPState */
        TEPState: {
            /**
             * Profile
             * @default nist-teinit-base-case-v1
             * @constant
             */
            profile: "nist-teinit-base-case-v1";
            /**
             * Data Origin
             * @default simulation
             * @constant
             */
            data_origin: "simulation";
            /** Configured At */
            configured_at: number;
            /** Model Version */
            model_version: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Wrapper Sha256 */
            wrapper_sha256: string;
            /** Variables Sha256 */
            variables_sha256: string;
        };
        /** TEPVariable */
        TEPVariable: {
            /** Name */
            name: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "percent_full_scale" | "kscm/h" | "kg/h" | "kPa_gauge" | "percent" | "degC" | "m3/h" | "kW" | "mole_percent";
        };
        /** UnknownExecution */
        UnknownExecution: {
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @constant
             */
            status: "unknown";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    catalog_evidence_catalog_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_state_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_requests_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_requests__request_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_feedback_requests__request_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordFeedback"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_requests__request_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_evaluation_requests__request_id__evaluation_cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_requests__request_id__decisions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_requests__request_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_state_demo_state_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoStateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_virtual_time_demo_advance_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoAdvanceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_virtual_state_demo_sample_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_virtual_state_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_contact_requests__request_id__review_contact_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewContact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_notifications_requests__request_id__notifications_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_notification_requests__request_id__notifications__notification_id__send_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-iron-man-token"?: string | null;
            };
            path: {
                request_id: string;
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
