/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_requests_get"];
        put?: never;
        /** Create */
        post: operations["create_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_requests__request_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_requests__request_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_requests__request_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_requests__request_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change State */
        post: operations["change_state_demo_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppliedExecution */
        AppliedExecution: {
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @constant
             */
            status: "applied";
            /**
             * Virtual
             * @constant
             */
            virtual: true;
            command: components["schemas"]["Command-Output"];
            state: components["schemas"]["Snapshot"];
        };
        /** Approval */
        Approval: {
            /** Actor */
            actor: string;
            /** Report Digest */
            report_digest: string;
            /** Expires At */
            expires_at: number;
            /** Reason */
            reason: string;
        };
        /** AuditEvent */
        AuditEvent: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "created" | "evaluation_failed" | "evaluated" | "approve" | "reject" | "execution_denied" | "execution_reserved" | "executed" | "execution_unknown" | "evaluation_interrupted" | "execution_interrupted";
            /** At */
            at: number;
            /** Verdict */
            verdict: ("draft" | "evaluating" | "blocked" | "hold" | "awaiting_approval" | "approved" | "rejected" | "revalidation_required" | "executing" | "completed" | "execution_unknown") | null;
            /** Report Digest */
            report_digest: string | null;
            /** Actor */
            actor: string | null;
            /** Reason */
            reason: string | null;
            /** Execution Id */
            execution_id: string | null;
        };
        /** Command */
        "Command-Input": {
            /**
             * Type
             * @default set_pump_speed
             * @constant
             */
            type: "set_pump_speed";
            /** Target Pct */
            target_pct: number;
            /**
             * Duration S
             * @default 300
             */
            duration_s: number;
        };
        /** Command */
        "Command-Output": {
            /**
             * Type
             * @default set_pump_speed
             * @constant
             */
            type: "set_pump_speed";
            /** Target Pct */
            target_pct: number;
            /**
             * Duration S
             * @default 300
             */
            duration_s: number;
        };
        /** DecisionInput */
        DecisionInput: {
            /** Report Digest */
            report_digest: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason: string;
        };
        /** DecisionReport */
        DecisionReport: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Revision */
            revision: number;
            /** Command Digest */
            command_digest: string;
            snapshot: components["schemas"]["Snapshot"];
            /** Snapshot Digest */
            snapshot_digest: string;
            /** Model Version */
            model_version: string;
            /** Policy Version */
            policy_version: string;
            /** Mock */
            mock: boolean;
            /** Can Approve */
            can_approve: boolean;
            evidence: components["schemas"]["EvidenceReview"] | null;
            simulation: components["schemas"]["SimulationResult"] | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "blocked" | "hold" | "awaiting_approval";
            /**
             * Reason Code
             * @enum {string}
             */
            reason_code: "INVALID_STATE" | "POLICY_VIOLATION" | "LIMIT_EXCEEDED" | "DEMO_PASS" | "EVIDENCE_INCOMPLETE" | "SIMULATION_INCOMPLETE" | "MODULE_FAILURE" | "LIVE_POLICY_NOT_CONFIGURED";
            /** Reason */
            reason: string;
            /** Digest */
            digest: string;
        };
        /** DemoStateInput */
        DemoStateInput: {
            /** Load Ratio */
            load_ratio: number;
            /**
             * Sensor Quality
             * @default valid
             * @enum {string}
             */
            sensor_quality: "valid" | "invalid";
        };
        /** EvidenceCard */
        EvidenceCard: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "support" | "counter" | "limitation";
            /** Claim */
            claim: string;
            /**
             * Applicability
             * @enum {string}
             */
            applicability: "applicable" | "partial" | "mismatch" | "unknown";
            /** Locator */
            locator: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "team_authored_fixture" | "paper" | "manual" | "field_record";
            /** Matched Conditions */
            matched_conditions: string[];
            /** Missing Conditions */
            missing_conditions: string[];
        };
        /** EvidenceReview */
        EvidenceReview: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mock */
            mock: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "demo_fixture" | "completed" | "insufficient" | "failed";
            /** Cards */
            cards: components["schemas"]["EvidenceCard"][];
            /** Proposed Tests */
            proposed_tests: components["schemas"]["Scenario"][];
            /** Limitation */
            limitation: string;
        };
        /** ExecutionInput */
        ExecutionInput: {
            /** Report Digest */
            report_digest: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewRequest */
        "NewRequest-Input": {
            /**
             * Equipment Id
             * @default cooling-demo-01
             * @constant
             */
            equipment_id: "cooling-demo-01";
            /**
             * Purpose
             * @default 냉각 펌프 속도 변경 검토
             */
            purpose: string;
            command: components["schemas"]["Command-Input"];
        };
        /** NewRequest */
        "NewRequest-Output": {
            /**
             * Equipment Id
             * @default cooling-demo-01
             * @constant
             */
            equipment_id: "cooling-demo-01";
            /**
             * Purpose
             * @default 냉각 펌프 속도 변경 검토
             */
            purpose: string;
            command: components["schemas"]["Command-Output"];
        };
        /** RequestHistory */
        RequestHistory: {
            /** Reports */
            reports: components["schemas"]["DecisionReport"][];
            /** Approvals */
            approvals: components["schemas"]["Approval"][];
        };
        /** RequestRecord */
        RequestRecord: {
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            request: components["schemas"]["NewRequest-Output"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "evaluating" | "blocked" | "hold" | "awaiting_approval" | "approved" | "rejected" | "revalidation_required" | "executing" | "completed" | "execution_unknown";
            report: components["schemas"]["DecisionReport"] | null;
            approval: components["schemas"]["Approval"] | null;
            /** Execution */
            execution: components["schemas"]["AppliedExecution"] | components["schemas"]["UnknownExecution"] | null;
            /** Events */
            events: components["schemas"]["AuditEvent"][];
        };
        /** Scenario */
        Scenario: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "normal" | "degraded_cooling";
            /** Evidence Id */
            evidence_id: string | null;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "normal" | "degraded_cooling";
            /** Evidence Id */
            evidence_id: string | null;
            /** Baseline Peak C */
            baseline_peak_c: number;
            /** Candidate Peak C */
            candidate_peak_c: number;
            /** Limit C */
            limit_c: number;
            /** Exceeded */
            exceeded: boolean;
            /**
             * Value Origin
             * @enum {string}
             */
            value_origin: "hardcoded_demo_fixture" | "model_calculation";
        };
        /** SimulationResult */
        SimulationResult: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mock */
            mock: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "out_of_domain" | "failed";
            /** Model Version */
            model_version: string;
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioResult"][];
            /** Limitation */
            limitation: string;
        };
        /** Snapshot */
        Snapshot: {
            /** Revision */
            revision: number;
            /** Temperature C */
            temperature_c: number;
            /** Load Ratio */
            load_ratio: number;
            /** Pump Speed Pct */
            pump_speed_pct: number;
            /** Observed At */
            observed_at: number;
            /**
             * Sensor Quality
             * @default valid
             * @enum {string}
             */
            sensor_quality: "valid" | "invalid";
            /**
             * Data Origin
             * @default synthetic
             * @constant
             */
            data_origin: "synthetic";
        };
        /** UnknownExecution */
        UnknownExecution: {
            /** Execution Id */
            execution_id: string;
            /**
             * Status
             * @constant
             */
            status: "unknown";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    state_state_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_requests_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRequest-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_requests__request_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_requests__request_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_requests__request_id__decisions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_requests__request_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_state_demo_state_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoStateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
